apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: argocd
spec:
  project: default

  source:
    path: jupyter
    targetRevision: HEAD
    repoURL: https://github.com/mowe49/ArgocdTest.git
  destination:
    namespace: jupyter
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true